mutation CaptureEmail($email: String!) {
  captureEmail(email: $email) {
    id
    email
    role
    status
    createdAt
  }
}

mutation SignUp(
  $id: String!
  $firstName: String!
  $lastName: String!
  $password: String!
) {
  signUp(
    id: $id
    firstName: $firstName
    lastName: $lastName
    password: $password
  ) {
    token
    user {
      id
      email
    }
  }
}
